# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- test

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UseRubyVersion@0
  displayName: 'Use Ruby >= 2.4'

- script: 'gem install bundler' 
  displayName: 'Install bundler'

- script: 'bundle install'
  displayName: 'Install Jekyll and Dependencies'

- script : |
    npm install
    JEKYLL_ENV=production gulp build --gulpfile gulpfile.js
  displayName: 'npm install and run gulp build'

- script: docker run --rm -d --name blog-for-test -p 80:80 -v "$(System.DefaultWorkingDirectory)/_site:/usr/share/nginx/html" nginx 
  displayName: launch docker nginx for test run

- script: npm test
  displayName: run tests

- script: docker stop blog-for-test

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: _site'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/_site'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
